### ISSUE TITLE
Unable to influence mancenter image tag

### ISSUE THREAD

**Issue by robinroos** [hazelcast/hazelcast-operator#49]
Hello,

I use OpenShift Operator for Hazelcast (v0.3.6) to deploy only Hazelcast Management Center.

My cluster, deployed seperately as Hazelcast embedded in a SpiringBoot application, is version 5.0-SNAPSHOT.

The deployed version of mancenter cannot support the version of the cache instance:

`Cluster version 5.0 is not compatible with this version of Management Center (4.2021.03)`

I am attempting to cause the Operator to install the 5.0-BETA-1 version of Management Center, which does exist on hub.docker.com.  No matter what I do, the resulting StatefulSet always has:

`image: 'hazelcast/management-center:4.2021.03'`

Below is the best config I have so far, applied in the Operator after deleting the only Hazelcast and then recreating it, using YAML inputs.

```
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hz
  namespace: bento
spec:
  securityContext:
    runAsUser: ''
    runAsGroup: '0'
    fsGroup: ''
  hazelcast:
    enabled: false
  mancenter:
    enabled: true
    image:
      tag: "5.0-BETA-1"
    adminCredentialsSecretName: mancenter-admin-credentials-secret
    persistence:
      existingClaim: hazelcast-mancenter-data
```

Can anyone spot my mistake?
